version: '3.9'
services:
  app:
    image: learn-svelte
    build: 
      context: .
      args:
        - BASE_IMAGE=node:lts-slim
    environment:
      - NODE_ENV=production
    ports:
      - 8000:8000
    expose:
      - 8000
    command: "npm start"
    
